import type { Locale } from "./schemas/classification.ts";

const copy = {
  "ja-JP": {
    eyebrow: "AIごみ分別",
    title: "これはどう捨てる？",
    subtitle: "写真を撮ると、台湾・日本の分別手順がわかります。",
    region: "地域ルール",
    municipality: "自治体",
    unspecifiedMunicipality: "未指定・その他",
    language: "表示言語",
    locate: "現在地を確認",
    upload: "写真を選ぶ",
    live: "カメラで確認",
    chooseTitle: "写真を選択",
    chooseHint: "1〜3点を明るい場所で撮影してください",
    cameraOff: "カメラはまだ起動していません",
    consent: "画像を Google Gemini に送信することに同意します。無料プランの内容は Google 製品の改善に使われる場合があります。",
    consentHint: "続けるには画像送信への同意が必要です。",
    classify: "分別を確認",
    classifying: "品目と地域ルールを確認中…",
    start: "カメラを起動",
    stop: "停止",
    capture: "撮影",
    emptyTitle: "結果はここに表示されます",
    emptyUpload: "写真を選ぶと、捨て先と準備手順を表示します。",
    emptyLive: "カメラを起動すると、自動で品目を確認します。",
    feedbackTitle: "判定を報告",
    feedbackItem: "報告する品目",
    correctLabel: "正しい分類",
    note: "補足説明",
    submit: "送信",
    close: "閉じる",
    again: "別の写真を確認",
    detected: "検出",
    itemUnit: "件",
    parts: "分別する部分",
    partUnit: "個",
    dispose: "捨て先",
    prepare: "処理",
    exception: "例外",
    lowConfidence: "不確かなため、角度を変えてもう一度撮影してください",
    report: "報告",
    details: "認識情報",
  },
  "zh-TW": {
    eyebrow: "AI 垃圾分類",
    title: "今天要丟什麼？",
    subtitle: "拍下物品，取得台灣或日本的分類步驟。",
    region: "法規地區",
    municipality: "城市／縣市",
    unspecifiedMunicipality: "未指定／其他",
    language: "顯示語言",
    locate: "偵測位置",
    upload: "從相簿選擇",
    live: "開啟相機",
    chooseTitle: "選擇垃圾圖片",
    chooseHint: "建議一次放入 1–3 件物品，並保持光線充足",
    cameraOff: "相機尚未啟動",
    consent: "我同意將影像傳送至 Google Gemini；免費方案內容可能用於改善 Google 產品。",
    consentHint: "請先同意影像傳送，才能開始辨識。",
    classify: "查看分類方式",
    classifying: "正在確認物品與當地規則…",
    start: "開啟相機",
    stop: "停止",
    capture: "拍攝確認",
    emptyTitle: "分類結果會顯示在這裡",
    emptyUpload: "選擇圖片後，我們會整理丟棄位置與處理步驟。",
    emptyLive: "啟動相機後，系統會自動辨識物品。",
    feedbackTitle: "回報判斷",
    feedbackItem: "回報的垃圾項目",
    correctLabel: "正確分類",
    note: "補充說明",
    submit: "送出",
    close: "關閉",
    again: "再辨識一張",
    detected: "辨識到",
    itemUnit: "項",
    parts: "需要拆分",
    partUnit: "個部分",
    dispose: "丟到",
    prepare: "處理",
    exception: "例外",
    lowConfidence: "辨識不確定，請換個角度再拍一次",
    report: "回報",
    details: "辨識資訊",
  },
} as const;

export function classifierCopy(locale: Locale) {
  return copy[locale === "ja-JP" ? "ja-JP" : "zh-TW"];
}
